export const APP_START = '@app/APP_START';
export const STORE_SCHEMAS = '@app/STORE_SCHEMAS';
export const FETCH_PROJECT_DETAILS = '@app/FETCH_PROJECT_DETAILS';
export const FETCH_PROJECT_DETAILS_SUCCESS =
  '@app/FETCH_PROJECT_DETAILS_SUCCESS';
export const FETCH_PROJECT_DETAILS_ERROR = '@app/FETCH_PROJECT_DETAILS_ERROR';
