export const SET_EVENTS_COLLECTIONS = '@events/SET_EVENTS_COLLECTIONS';

export const FETCH_COLLECTION_SCHEMA = '@events/FETCH_COLLECTION_SCHEMA';
export const FETCH_COLLECTION_SCHEMA_SUCCESS =
  '@events/FETCH_COLLECTION_SCHEMA_SUCCESS';
export const FETCH_COLLECTION_SCHEMA_ERROR =
  '@events/FETCH_COLLECTION_SCHEMA_ERROR';
export const SET_COLLETION_SCHEMA_LOADING =
  '@events/SET_COLLETION_SCHEMA_LOADING';
export const SCHEMA_COMPUTED = '@events/SCHEMA_COMPUTED';
